# @package _group_
data_dir: data/phase1-main/DATA
data_sources: 
  -
    name: "main"
    train_mos_list_path: data/sets/train.txt
    val_mos_list_path: data/sets/val.txt
    test_mos_list_path: data/sets/ev.txt
    wav_dir: data/wav
    data_dir: data/
    outfile: answer-main.csv
use_data:
  main: True
datamodule: 
  _target_: dataset.DataModule
#### only_meanは、平均値しか入手できないシナリオのこと。
only_mean: False
additional_datas:
  -
    _target_: dataset.NormalizeScore
    org_max: 10.0
    org_min: 0.0
    normalize_to_max: 1.0
    normalize_to_min: -1.0