# @package _group_
lightning_module: 
  _target_: lightning_module.BaselineLightningModule
WavLM: False

feature_extractors:
  -
    _target_: model.SSL_model

  -
    _target_: model.PhonemeEncoder
    hidden_dim: 256
    emb_dim: 256
    out_dim: 256
    n_lstm_layers: 3

output_layers:
  -
    _target_: model.LDConditioner
  -
   _target_: model.Projection
   hidden_dim: 2048
   activation:
    _target_: torch.nn.ReLU
   range_clipping: False

